namespace NodeJS {
  interface ProcessEnv {
    // AppWrite
    EXPO_PUBLIC_APPWRITE_PROJECT_ID: string;
    EXPO_PUBLIC_APPWRITE_API_BASE_URL: string;
    EXPO_PUBLIC_APPWRITE_API_VERSION: string;
    EXPO_PUBLIC_APPWRITE_PROJECT_PLATFORM: string;
    EXPO_PUBLIC_APPWRITE_DATABASE_ID: string;
    EXPO_PUBLIC_APPWRITE_AGENTS_COLLECTION_ID: string;
    EXPO_PUBLIC_APPWRITE_GALLERIES_COLLECTION_ID: string;
    EXPO_PUBLIC_APPWRITE_REVIEWS_COLLECTION_ID: string;
    EXPO_PUBLIC_APPWRITE_PROPERTIES_COLLECTION_ID: string;
  }
}
